# -*- coding: utf-8 -*-
"""Are this vault's generated files still what the generator wrote?

Copied verbatim into `<vault>/_system/scripts/` so the check survives without the plugin.

    py stamp_check.py <vault-root> [--json]

Walks every `.md` and `.base` carrying a `generated-by:` stamp and reports one of:

    CLEAN        body matches its stamp
    HAND-EDITED  body does not. A defect: the next regeneration would silently discard it
    UNSTAMPED    claims to be generated in its own text but carries no stamp

STALE is not decidable here, because the sources live with the generator, not the vault.
Saying so is the point: a checker that implied it could tell would be claiming coverage
it does not have. `place check` resolves STALE; this script never pretends to.

Exit 1 on any HAND-EDITED.
"""
import io
import json
import os
import re
import sys

# The shared argument reader, beside this file in `_system/scripts/`. Imported by path rather
# than by package, because these scripts are copied into a vault and run standalone.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _args                                                        # noqa: E402

USAGE = '''\
usage: stamp_check.py [<vault>] [--json]
  has a generated region been hand-edited'''


sys.stdout.reconfigure(encoding='utf-8')

VOLATILE = [r'^\s*columnSize:', r'^\s*viewport:', r'^\s{2,}[A-Za-z0-9_.]+:\s*\d+\s*$']
CLAIMS_GENERATED = re.compile(r'GENERATED|autogenerated|автогенер', re.I)
SKIP_DIRS = {'.obsidian', '.trash', '.git', 'node_modules', '__pycache__'}
# `.claude/` is NOT skipped wholesale. The engine writes stamped, region-bearing files into
# these two subtrees, and skipping the directory made them unchecked: a hand-edited region in
# a SKILL.md or an agent was invisible to the one tool whose job is to notice. Only these
# subtrees are read, so a third-party file elsewhere under `.claude/` remains none of our
# business - and an unstamped file is reported only when it CLAIMS to be generated.
CLAUDE_SUBTREES = ('.claude/skills', '.claude/agents', '.claude/workflows')


def _norm(text):
    text = text.replace('\r\n', '\n').replace('\r', '\n')
    return '\n'.join(l.rstrip() for l in text.split('\n')).rstrip('\n') + '\n'


def _sha(text):
    import hashlib
    return hashlib.sha256(_norm(text).encode('utf-8')).hexdigest()[:16]


def _hash(text, is_base):
    """Hash the bytes the WRITER hashed.

    The engine strips volatile lines for `.base` files and for nothing else, because Obsidian
    rewrites `columnSize` into a `.base` it opens and rewrites nothing into a Markdown file.
    Stripping them everywhere made the reader and the writer disagree on any file carrying an
    indented `key: <digits>` line - which is every SKILL.md and every agent at standard tier,
    via `contract_version: 1`.
    """
    return _sha(_strip_volatile(text) if is_base else text)


def _strip_volatile(text):
    rx = [re.compile(p) for p in VOLATILE]
    return '\n'.join(l for l in text.split('\n') if not any(r.search(l) for r in rx))


def _split(text):
    if not text.startswith('---'):
        return None, text
    nl = text.find('\n')
    if nl == -1 or text[3:nl].strip():
        return None, text
    end = text.find('\n---', nl)
    while end != -1:
        after = end + 4
        if after >= len(text) or text[after] in '\r\n':
            return text[nl + 1:end], text[after:].lstrip('\r\n')
        end = text.find('\n---', end + 1)
    return None, text


def _field(fm_text, key):
    if not fm_text:
        return None
    m = re.search(r'^%s:\s*(.+?)\s*$' % re.escape(key), fm_text, re.M)
    return m.group(1).strip('"\'') if m else None


_BEGIN = re.compile(
    r'^[ \t]*(?:#|//)?[ \t]*<!--[ \t]*solai:begin[ \t]+([A-Za-z0-9_-]+)'
    r'(?:[ \t]+src=(\S*))?(?:[ \t]+body=(\S*))?[ \t]*-->[ \t]*$', re.M)


def _regions(text, is_base=False):
    """-> [(region_id, declared_sha, actual_sha)] for every well-formed region."""
    out = []
    for m in _BEGIN.finditer(text):
        rid, declared = m.group(1), m.group(3) or ''
        end = re.search(r'^[ \t]*(?:#|//)?[ \t]*<!--[ \t]*solai:end[ \t]+%s[ \t]*-->[ \t]*$'
                        % re.escape(rid), text[m.end():], re.M)
        if not end:
            continue
        content = text[m.end():m.end() + end.start()].strip('\n')
        out.append((rid, declared, _hash(content, is_base)))
    return out


def scan(root):
    findings = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        rel_dir = os.path.relpath(dirpath, root).replace(os.sep, '/')
        # Descend through `.claude/` to reach the declared subtrees, but read files only
        # inside them. `continue` skips this directory's files without pruning its children.
        if rel_dir.startswith('.claude') and not any(
                rel_dir == s or rel_dir.startswith(s + '/') for s in CLAUDE_SUBTREES):
            continue
        for name in filenames:
            if not name.endswith(('.md', '.base', '.js')):
                continue
            path = os.path.join(dirpath, name)
            try:
                with io.open(path, encoding='utf-8') as fh:
                    text = fh.read()
            except (OSError, UnicodeDecodeError):
                continue
            fm_text, body = _split(text)
            declared = _field(fm_text, 'body-sha')
            rel = os.path.relpath(path, root).replace(os.sep, '/')
            if declared:
                actual = _hash(body, name.endswith('.base'))
                findings.append({
                    'path': rel,
                    'state': 'CLEAN' if actual == declared else 'HAND-EDITED',
                    'declared': declared, 'actual': actual,
                })
                continue
            # A merged file carries no file-level stamp: its generated parts are stamped
            # region by region, so the user can edit the prose around them freely. Check
            # those instead of calling the whole file unstamped.
            regs = _regions(text, name.endswith('.base'))
            if regs:
                for rid, dec, act in regs:
                    findings.append({
                        'path': '%s [%s]' % (rel, rid),
                        'state': 'CLEAN' if dec == act else 'HAND-EDITED',
                        'declared': dec, 'actual': act,
                    })
            elif CLAIMS_GENERATED.search(text[:4000]):
                findings.append({'path': rel, 'state': 'UNSTAMPED',
                                 'declared': None, 'actual': None})
    return findings


def main():
    root, opts, done = _args.parse(sys.argv[1:], USAGE, flags=('--json',), values=())
    if done:
        print(done[1])
        return done[0]
    findings = scan(root)
    if opts['--json']:
        print(json.dumps(findings, ensure_ascii=False, indent=2))
    else:
        bad = [f for f in findings if f['state'] != 'CLEAN']
        print('stamped files: %d   clean: %d   hand-edited: %d   unstamped: %d' % (
            len([f for f in findings if f['declared']]),
            len([f for f in findings if f['state'] == 'CLEAN']),
            len([f for f in findings if f['state'] == 'HAND-EDITED']),
            len([f for f in findings if f['state'] == 'UNSTAMPED'])))
        for f in bad:
            print('  %-12s %s' % (f['state'], f['path']))
        if not bad:
            print('  all stamped files match.')
    return 1 if any(f['state'] == 'HAND-EDITED' for f in findings) else 0


if __name__ == '__main__':
    sys.exit(main())
