# -*- coding: utf-8 -*-
"""Author a new agent or workflow declaration, and wire it into the archetypes that take it.

    py author.py agent <name> --job "..." --returns "..." --eval "..." [--archetype a,b] [--apply]
    py author.py workflow <name> --goal "..." --input "..." --output "..." --phase "..." [--apply]
    py author.py class add <name> --prefix XXX --folder <dir> --purpose "..." \
        --status "lifecycle=a,b;terminal=c" --field "name=..;type=..;meaning=.." \
        --archetype <a> [--link "field=..;target=..;kind=.."] [--h2 "## ..."] [--apply]
    py author.py class rename <old> <new> --archetype <a> [--apply]
    py author.py class retire <name> --archetype <a> [--apply]

`--plan` is the default and writes nothing, like every other entry point here.

WHY THIS EXISTS. Before it, adding an agent meant editing the package by hand: write a TOML,
remember to add the name to each manifest's list, remember that the list is a top-level key that
TOML swallows if it drifts below a table header, then re-run the engine. Four agents and three
workflows were authored that way, and the cost of that is exactly what these verbs remove.

THE ONE RULE THAT SHAPES IT. A declaration is only written if it LOADS. The content is required
on the command line rather than scaffolded as placeholders, because a placeholder declaration
either fails the loader on the next run - leaving the package broken for whoever runs it next -
or passes it while meaning nothing. So the substantive fields are arguments, the result is
validated in memory before anything is planned, and a refusal names what is missing.

It writes DECLARATIONS only. Projections are regenerated by the engine afterwards, which is the
whole point: nothing here hand-edits a projected file, and the last thing this prints is the
command that regenerates them.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(os.path.dirname(HERE))              # .../plugins/solai
sys.path.insert(0, os.path.dirname(PKG))
sys.path.insert(0, PKG)

from lib import decl, fsplan, VERSION                              # noqa: E402

sys.stdout.reconfigure(encoding='utf-8')

MANIFEST = '.author/last-apply.json'
BACKUP = '.author/_backup'

# Two jobs that share most of their significant words are one job with two names.
#
# CONTAINMENT, not Jaccard. Jaccard divides by the union, so a short job that is entirely a
# SUBSET of a long existing one scores low - and a subset is the clearest duplicate there is.
# Restating scout's first sentence scored 0.43 against its full job and sailed through, which is
# how this was found. Containment divides by the smaller set, so a subset scores 1.0.
OVERLAP = 0.6
STOP = set('a an the and or of to in on for that this it is are be with from by as at not '
           'you your they them what which when each every one two into onto out over under '
           'do does did done its their his her'.split())


def _words(text):
    return {w for w in re.findall(r'[a-z]+', (text or '').lower()) if w not in STOP and len(w) > 2}


def _kv(spec):
    """`key=value;key=value` -> dict. Values may contain anything but a semicolon."""
    out = {}
    for part in spec.split(';'):
        if not part.strip():
            continue
        k, _, v = part.partition('=')
        out[k.strip()] = v.strip()
    return out


def _toml_str(value):
    """A TOML basic string. Multi-line prose is emitted as one line: a declaration field is a
    sentence, not a document, and the loader's minimum lengths are about substance not shape."""
    s = str(value).replace('\\', '\\\\').replace('"', '\\"').replace('\n', ' ')
    return '"%s"' % re.sub(r'\s+', ' ', s).strip()


def _toml_list(values):
    return '[%s]' % ', '.join(_toml_str(v) for v in values)


# --------------------------------------------------------------------------- render

def agent_toml(name, o):
    lines = ['schema = 1', '']
    if o.get('why'):
        lines += ['# %s' % o['why'], '']
    lines += [
        'agent = %s' % _toml_str(name),
        'title = %s' % _toml_str(o.get('title') or name.replace('-', ' ').title()),
        'job   = %s' % _toml_str(o['job']),
    ]
    if o.get('sent-when'):
        lines.append('sent_when = %s' % _toml_str(o['sent-when']))
    lines += [
        'model   = %s' % _toml_str(o.get('model', 'inherit')),
        'tools   = %s' % _toml_list(o.get('tools') or ['Read', 'Grep', 'Glob']),
        'writes  = %s' % ('true' if o.get('writes') else 'false'),
        'induces = %s' % _toml_str(o.get('induces', 'none')),
    ]
    if o.get('reads'):
        lines.append('reads = %s' % _toml_list(o['reads']))
    if o.get('refuses'):
        lines.append('refusals = %s' % _toml_list(o['refuses']))
    lines += ['', '[returns]',
              'kind    = %s' % _toml_str(o.get('returns-kind', 'records')),
              'meaning = %s' % _toml_str(o.get('returns-meaning', o['job']))]
    for spec in o['returns']:
        d = _kv(spec)
        lines += ['', '[[returns.fields]]',
                  'name     = %s' % _toml_str(d.get('name', '')),
                  'type     = %s' % _toml_str(d.get('type', 'scalar')),
                  'required = %s' % ('true' if d.get('required', 'true') != 'false' else 'false')]
        if d.get('values'):
            lines.append('values   = %s' % _toml_list(d['values'].split(',')))
        if d.get('of'):
            lines.append('of       = %s' % _toml_list(d['of'].split(',')))
        lines.append('meaning  = %s' % _toml_str(d.get('meaning', '')))
    for spec in o['evals']:
        d = _kv(spec)
        lines += ['', '[[evals]]',
                  'id         = %s' % _toml_str(d.get('id', '')),
                  'asserts    = %s' % _toml_str(d.get('asserts', '')),
                  'fails_when = %s' % _toml_str(d.get('fails_when', d.get('fails', '')))]
    return '\n'.join(lines) + '\n'


def workflow_toml(name, o):
    lines = ['schema = 1', '']
    if o.get('why'):
        lines += ['# %s' % o['why'], '']
    lines += [
        'workflow = %s' % _toml_str(name),
        'title    = %s' % _toml_str(o.get('title') or name.replace('-', ' ').title()),
        'goal     = %s' % _toml_str(o['goal']),
        'input    = %s' % _toml_str(o['input']),
        'output   = %s' % _toml_str(o['output']),
    ]
    if o.get('run-when'):
        lines.append('run_when = %s' % _toml_str(o['run-when']))
    for i, spec in enumerate(o['phases'], 1):
        d = _kv(spec)
        lines += ['', '[[phases]]',
                  'n     = %d' % i,
                  'title = %s' % _toml_str(d.get('title', '')),
                  'agent = %s' % _toml_str(d.get('agent', '')),
                  'shape = %s' % _toml_str(d.get('shape', 'pipeline')),
                  'over  = %s' % _toml_str(d.get('over', ''))]
        if d.get('carry'):
            lines.append('carry = %s' % _toml_str(d['carry']))
        if d.get('barrier_because') or d.get('because'):
            lines.append('barrier_because = %s'
                         % _toml_str(d.get('barrier_because') or d.get('because')))
        if d.get('detail'):
            lines.append('detail = %s' % _toml_str(d['detail']))
    return '\n'.join(lines) + '\n'



def class_toml(name, o):
    """Render a card-class declaration.

    Everything `_validate_class` requires is taken from the command line, never defaulted into
    existence: a class with an invented prefix or a guessed status set loads fine and means
    nothing, which is the failure mode this whole entry point exists to prevent.
    """
    st = _kv(o.get('status', ''))
    lifecycle = [x.strip() for x in st.get('lifecycle', '').split(',') if x.strip()]
    terminal = [x.strip() for x in st.get('terminal', '').split(',') if x.strip()]
    default = st.get('default') or (lifecycle[0] if lifecycle else '')
    skill = o.get('skill') or name
    filename = o.get('filename', 'bare-id')

    lines = ['schema = 1', '']
    if o.get('why'):
        lines += ['# %s' % o['why'], '']
    lines += [
        'class     = %s' % _toml_str(name),
        'prefix    = %s' % _toml_str(o['prefix']),
        'folder    = %s' % _toml_str(o['folder']),
        'skill     = %s' % _toml_str(skill),
        'title     = %s' % _toml_str(o.get('title') or name.replace('-', ' ').title()),
        'purpose   = %s' % _toml_str(o['purpose']),
        'minted_by = %s' % _toml_str('skill:%s' % skill),
        'filename  = %s' % _toml_str(filename),
    ]
    if o.get('archive-folder'):
        lines.append('archive_folder = %s' % _toml_str(o['archive-folder']))

    lines += ['', '[status]']
    if lifecycle:
        lines.append('lifecycle = %s' % _toml_list(lifecycle))
    if terminal:
        lines.append('terminal  = %s' % _toml_list(terminal))
    if default:
        lines.append('default   = %s' % _toml_str(default))
    notes = [_kv(n) for n in o.get('status_notes', [])]
    notes = [(d.get('value', ''), d.get('note', '')) for d in notes]
    notes = [(v, n) for v, n in notes if v]
    if notes:
        lines += ['', '[status.notes]']
        for v, n in notes:
            lines.append('%s = %s' % (_toml_str(v), _toml_str(n)))
    lines += ['', '[status.rules]',
              'terminal_callout        = true',
              'terminal_relaxes_schema = false']

    for spec in o['fields']:
        d = _kv(spec)
        lines += ['', '[[fields]]',
                  'name    = %s' % _toml_str(d.get('name', '')),
                  'type    = %s' % _toml_str(d.get('type', 'scalar')),
                  'card    = %s' % _toml_str(d.get('card', '0..1'))]
        if d.get('required', '').lower() in ('true', 'yes', '1'):
            lines.append('required = true')
        if d.get('values'):
            lines.append('values  = %s' % _toml_list(
                [v.strip() for v in d['values'].split(',') if v.strip()]))
        if d.get('source'):
            lines.append('source  = %s' % _toml_str(d['source']))
        if d.get('no_default', '').lower() in ('true', 'yes', '1'):
            lines.append('no_default = true')
        if d.get('derived_by'):
            lines.append('derived_by = %s' % _toml_str(d['derived_by']))
        lines.append('meaning = %s' % _toml_str(d.get('meaning', '')))

    for spec in o['links']:
        d = _kv(spec)
        lines += ['', '[[links]]',
                  'field   = %s' % _toml_str(d.get('field', '')),
                  'target  = %s' % _toml_str(d.get('target', '')),
                  'card    = %s' % _toml_str(d.get('card', '0..N')),
                  'kind    = %s' % _toml_str(d.get('kind', 'one-way'))]
        if d.get('reciprocal'):
            lines.append('reciprocal = %s' % _toml_str(d['reciprocal']))
        lines.append('meaning = %s' % _toml_str(d.get('meaning', '')))

    cite = o.get('cite', 'footnotes')
    lines += ['', '[body]']
    if o['h2s']:
        lines.append('required_h2 = %s' % _toml_list(o['h2s']))
    if o['optional_h2s']:
        lines.append('optional_h2 = %s' % _toml_list(o['optional_h2s']))
    if cite == 'footnotes':
        lines.append('sources_h3  = %s' % _toml_str('### Sources'))
    lines.append('cite_style  = %s' % _toml_str(cite))

    lines += ['', '[view]',
              'columns = %s' % _toml_list(class_view_columns(o, filename))]
    lines += ['', '[[view.sort]]',
              'property  = %s' % _toml_str('status'),
              'direction = %s' % _toml_str('ASC')]

    lines += ['', '[card-skill]',
              'modes    = %s' % _toml_list(
                  [m.strip() for m in o.get('modes', 'single').split(',') if m.strip()]),
              'shared   = %s' % _toml_list(
                  ['status-protocol', 'card-concision', 'block-id-protocol']),
              'rubrics  = %s' % _toml_list(class_rubrics(o)),
              'triggers = %s' % _toml_list(
                  [t.strip() for t in o.get('triggers', '').split(';') if t.strip()]),
              'induces  = %s' % _toml_str(o.get('induces', 'none'))]
    return '\n'.join(lines) + '\n'


def class_view_columns(o, filename):
    """`file.name`, then every declared name, then tags.

    Built rather than asked for, because `_validate_class` rejects a column that is not a
    declared field or link, and a view is the one projection nobody reads until it is wrong.
    """
    if o.get('view'):
        return [c.strip() for c in o['view'].split(',') if c.strip()]
    cols = ['file.name']
    if filename == 'slug':
        cols.append('id')
    #  is named explicitly because the default sort is on it, and a view that orders by
    # a column it does not show is a view whose order looks arbitrary.
    cols.append('status')
    cols += [_kv(f).get('name', '') for f in o['fields']]
    cols += [_kv(l).get('field', '') for l in o['links']]
    cols = [c for c in cols if c]
    return cols + ['tags']


def class_rubrics(o):
    """A rubric is a `How to choose X` table in the generated skill. Offered for every enum the
    class declares, because an enum with no rubric is a list of words the author picks from by
    feel, and `severity` picked by feel is how a register ends up all-high."""
    if o.get('rubrics'):
        return [r.strip() for r in o['rubrics'].split(',') if r.strip()]
    out = []
    for f in o['fields']:
        d = _kv(f)
        if d.get('type') == 'enum' and d.get('values'):
            out.append(d.get('name', ''))
    return [r for r in out if r]


def prefix_taken(prefix, archetypes):
    """One prefix, one class, within any archetype this would be selected into."""
    for arch in archetypes:
        root = os.path.join(PKG, 'archetypes', arch, 'classes')
        if not os.path.isdir(root):
            continue
        for f in sorted(os.listdir(root)):
            if not f.endswith('.toml'):
                continue
            try:
                data = decl._read(os.path.join(root, f))
            except Exception:                                       # noqa: BLE001
                continue
            if (data.get('prefix') or '').upper() == prefix.upper():
                return ('prefix %r is already %r in archetype %r. An identifier prefix is how a '
                        'card is found, and two classes sharing one makes every ID ambiguous.'
                        % (prefix, data.get('class'), arch))
    return None

# --------------------------------------------------------------------------- manifest wiring

def add_to_list(text, key, name):
    """Append `name` to the top-level `key = [...]` line. Returns None when already present.

    The list is a TOML top-level key, so it must stay above the first table header: this edits
    the existing line in place rather than appending a new one anywhere, because a `key = [...]`
    written below a table header is silently swallowed into that table.
    """
    rx = re.compile(r'(?m)^(%s\s*=\s*\[)([^\]]*)(\])' % re.escape(key))
    m = rx.search(text)
    if not m:
        return None, '%s: no top-level `%s = [...]` line to extend' % (key, key)
    inner = m.group(2).strip()
    if re.search(r'"%s"' % re.escape(name), inner):
        return None, 'already listed'
    new_inner = ('%s, "%s"' % (inner, name)) if inner else '"%s"' % name
    return text[:m.start()] + m.group(1) + new_inner + m.group(3) + text[m.end():], None


# --------------------------------------------------------------------------- checks

def existing(kind):
    """Every declaration of this kind the package ships, from both search paths."""
    out = {}
    roots = [os.path.join(PKG, 'common', kind)]
    roots += [os.path.join(PKG, 'archetypes', a, kind)
              for a in sorted(os.listdir(os.path.join(PKG, 'archetypes')))]
    for r in roots:
        if not os.path.isdir(r):
            continue
        for f in sorted(os.listdir(r)):
            if f.endswith('.toml'):
                out[f[:-5]] = os.path.join(r, f)
    return out


def name_taken(name):
    """A name is one thing. An agent, a workflow and a card skill share one namespace."""
    for kind, label in (('agents', 'agent'), ('workflows', 'workflow'), ('classes', 'class')):
        if name in existing(kind):
            return 'the name %r is already a declared %s' % (name, label)
    return None


def job_overlap(job, kind='agents', field='job'):
    for other, path in sorted(existing(kind).items()):
        try:
            data = decl._read(path)
        except Exception:                                           # noqa: BLE001
            continue
        theirs = _words(data.get(field, ''))
        mine = _words(job)
        if not theirs or not mine:
            continue
        shared = len(mine & theirs) / float(min(len(mine), len(theirs)))
        if shared >= OVERLAP:
            return ('the declared %s repeats %d%% of the significant words in %r. Two jobs that '
                    'share most of their words are one job with two names: either sharpen this one '
                    'until it is doing something %r is not, or extend %r instead.'
                    % (field, round(shared * 100), other, other, other))
    return None



# --------------------------------------------------------------------------- rename and retire

# Only these keys ever hold a class NAME. `meaning` holds prose that mentions class names all
# the time ("The gap this bears on."), and rewriting prose on a rename is how a declaration
# ends up asserting something nobody wrote. Line-anchored, quoted, exact.
NAME_KEYS = ('class', 'skill', 'target', 'field', 'reciprocal')


def rename_in_toml(text, old, new):
    """Rewrite every key that holds the class name, and nothing else. Returns (text, hits)."""
    hits = 0
    for key in NAME_KEYS:
        rx = re.compile(r'(?m)^(\s*%s\s*=\s*)"%s"' % (re.escape(key), re.escape(old)))
        text, k = rx.subn(lambda m: '%s"%s"' % (m.group(1), new), text)
        hits += k
    rx = re.compile(r'(?m)^(\s*minted_by\s*=\s*)"skill:%s"' % re.escape(old))
    text, k = rx.subn(lambda m: '%s"skill:%s"' % (m.group(1), new), text)
    return text, hits + k


def remove_from_list(text, key, name):
    """Drop `name` from the top-level `key = [...]` line. Mirror of `add_to_list`."""
    rx = re.compile(r'(?m)^(%s\s*=\s*\[)([^\]]*)(\])' % re.escape(key))
    m = rx.search(text)
    if not m:
        return None, '%s: no top-level `%s = [...]` line to edit' % (key, key)
    items = [x.strip() for x in m.group(2).split(',') if x.strip()]
    kept = [x for x in items if x.strip('"') != name]
    if len(kept) == len(items):
        return None, 'not listed'
    return text[:m.start()] + m.group(1) + ', '.join(kept) + m.group(3) + text[m.end():], None


def class_paths(name, archetypes):
    """Where this class is declared, per archetype that declares it."""
    out = []
    for arch in archetypes:
        rel = 'archetypes/%s/classes/%s.toml' % (arch, name)
        if os.path.exists(os.path.join(PKG, rel.replace('/', os.sep))):
            out.append((arch, rel))
    return out


def class_references(name, archetypes, skip_own=True):
    """Everything outside this class's own declaration that still names it.

    This is the check a retirement turns on. `CHG-008` of the counselor vault deleted a class
    whose prefix an assertion still counted, and the gate read zero for sixty-four records
    before anyone read it as a defect rather than a finding. Four surfaces, all of them
    mechanical: sibling declarations, the manifest's own loop, the selection list, and a
    prefix written into a runtime checker.
    """
    hits = []
    prefix = None
    for arch, rel in class_paths(name, archetypes):
        try:
            prefix = (decl._read(os.path.join(PKG, rel.replace('/', os.sep))).get('prefix')
                      or prefix)
        except Exception:                                           # noqa: BLE001
            pass

    for arch in archetypes:
        root = os.path.join(PKG, 'archetypes', arch, 'classes')
        if os.path.isdir(root):
            for f in sorted(os.listdir(root)):
                if not f.endswith('.toml') or (skip_own and f == '%s.toml' % name):
                    continue
                try:
                    data = decl._read(os.path.join(root, f))
                except Exception:                                   # noqa: BLE001
                    continue
                for l in data.get('links', []):
                    if l.get('target') == name:
                        hits.append('archetypes/%s/classes/%s links `%s` at target %r'
                                    % (arch, f, l.get('field'), name))
                    if l.get('reciprocal') == name:
                        hits.append('archetypes/%s/classes/%s names %r as a reciprocal field'
                                    % (arch, f, name))
        mpath = os.path.join(PKG, 'archetypes', arch, 'manifest.toml')
        if os.path.exists(mpath):
            try:
                man = decl._read(mpath)
            except Exception:                                       # noqa: BLE001
                man = {}
            for step in man.get('loop', []):
                if re.search(r'/%s\b' % re.escape(name), str(step.get('skill', ''))):
                    hits.append('archetypes/%s/manifest.toml loop step %s calls `/%s`'
                                % (arch, step.get('n'), name))

    if prefix:
        rt = os.path.join(PKG, 'runtime')
        for f in sorted(os.listdir(rt)) if os.path.isdir(rt) else []:
            if not f.endswith('.py'):
                continue
            body = fsplan.read(os.path.join(rt, f))
            if re.search(r'["\']%s["\']' % re.escape(prefix), body):
                hits.append('runtime/%s hardcodes the prefix %r, so an assertion would keep '
                            'counting a class that no longer exists' % (f, prefix))
    return hits


def do_rename(o, old, new):
    """Rewrite the declaration and every key that names it. Projections are the engine's job."""
    problems = []
    if not new or new != new.lower() or '_' in new or ' ' in new:
        problems.append('the new name must be lowercase kebab-case: got %r' % new)
    taken = name_taken(new)
    if taken:
        problems.append(taken)
    if not o['archetypes']:
        problems.append('--archetype is required: a class is declared inside one.')
    found = class_paths(old, o['archetypes'])
    if o['archetypes'] and not found:
        problems.append('no class %r declared in %s.' % (old, ', '.join(o['archetypes'])))
    if problems:
        print('\nrefused:')
        for p in problems:
            print('  %s' % p)
        return 1

    plan = fsplan.Plan(PKG, VERSION)
    for arch, rel in found:
        body, _ = rename_in_toml(fsplan.read(os.path.join(PKG, rel.replace('/', os.sep))),
                                 old, new)
        plan.write('archetypes/%s/classes/%s.toml' % (arch, new), 'declaration', body)
        plan.delete(rel, 'declaration', reason='renamed to %s' % new)

        mrel = 'archetypes/%s/manifest.toml' % arch
        cur = fsplan.read(os.path.join(PKG, mrel.replace('/', os.sep)))
        cur = re.sub(r'(?m)^(classes\s*=\s*\[[^\]]*)"%s"' % re.escape(old),
                     lambda m: '%s"%s"' % (m.group(1), new), cur)
        cur = re.sub(r'(?m)^(\s*skill\s*=\s*"[^"]*)/%s\b' % re.escape(old),
                     lambda m: '%s/%s' % (m.group(1), new), cur)
        plan.write(mrel, 'selection', cur)

        root = os.path.join(PKG, 'archetypes', arch, 'classes')
        for f in sorted(os.listdir(root)):
            if not f.endswith('.toml') or f == '%s.toml' % old:
                continue
            srel = 'archetypes/%s/classes/%s' % (arch, f)
            body2, hits = rename_in_toml(
                fsplan.read(os.path.join(PKG, srel.replace('/', os.sep))), old, new)
            if hits:
                plan.write(srel, 'declaration', body2)

    print()
    print(plan.table())
    print('\n  The `folder` key is not renamed: a folder is a path, not a name, and moving the\n'
          '  cards already in it is a vault migration this verb does not perform.')
    print('  Vaults already built are unaffected. They read their own compiled declarations,\n'
          '  so their cards keep the old key until each is migrated on its own record.')
    return finish(plan, o)


def do_retire(o, name):
    """Delete the declaration, but only once nothing else in the package still names it."""
    problems = []
    if not o['archetypes']:
        problems.append('--archetype is required: a class is declared inside one.')
    found = class_paths(name, o['archetypes'])
    if o['archetypes'] and not found:
        problems.append('no class %r declared in %s.' % (name, ', '.join(o['archetypes'])))
    refs = class_references(name, o['archetypes']) if found else []
    if refs:
        problems.append('%d thing(s) still name %r. Retiring it now repeats CHG-008:'
                        % (len(refs), name))
        problems += ['  - %s' % r for r in refs]
    if problems:
        print('\nrefused:')
        for p in problems:
            print('  %s' % p)
        return 1

    plan = fsplan.Plan(PKG, VERSION)
    for arch, rel in found:
        plan.delete(rel, 'declaration', reason='retired')
        mrel = 'archetypes/%s/manifest.toml' % arch
        cur = fsplan.read(os.path.join(PKG, mrel.replace('/', os.sep)))
        new, err = remove_from_list(cur, 'classes', name)
        if err == 'not listed':
            plan.noop(mrel, 'selection', reason='not listed')
            continue
        if err:
            print('\nrefused: %s' % err)
            return 1
        plan.write(mrel, 'selection', new)

    print()
    print(plan.table())
    print('\n  The generated skill and the cards already written are NOT deleted here. The\n'
          '  engine reports the orphaned skill on the next run; the cards are evidence, and\n'
          '  what happens to them is a decision with a change record, not a side effect.')
    return finish(plan, o)


def finish(plan, o):
    """Apply or stop, then prove the package still loads. Shared by rename and retire."""
    if o['mode'] != 'apply':
        print('\nplan only. Nothing written. Re-run with --apply.')
        return 0
    fsplan.apply(plan, os.path.join(PKG, MANIFEST.replace('/', os.sep)),
                 backup_dir=os.path.join(PKG, BACKUP.replace('/', os.sep)))
    print('\napplied.')
    bad = []
    for arch in sorted(os.listdir(os.path.join(PKG, 'archetypes'))):
        try:
            decl.load_archetype(PKG, arch)
        except decl.DeclError as e:
            bad.append('%s:\n%s' % (arch, e))
    if bad:
        print('\nthe package no longer loads. Roll back with:')
        print('  py -c "import sys;sys.path.insert(0,r\'%s\');'
              'from lib import fsplan;print(fsplan.rollback(r\'%s\'))"'
              % (PKG, os.path.join(PKG, MANIFEST.replace('/', os.sep))))
        for b in bad:
            print('\n%s' % b)
        return 1
    print('every archetype still loads.')
    print('\nNext, and this is the part that is not optional: regenerate the projections.')
    print('  py %s/skills/solai-scaffold/scaffold.py "<place>" --apply' % PKG)
    return 0


# --------------------------------------------------------------------------- main

def parse(argv):
    o = {'archetypes': [], 'returns': [], 'evals': [], 'phases': [], 'tools': [],
         'reads': [], 'refuses': [], 'fields': [], 'links': [], 'h2s': [],
         'optional_h2s': [], 'status_notes': [], 'mode': 'plan'}
    i, positional = 0, []
    lists = {'--returns': 'returns', '--eval': 'evals', '--phase': 'phases',
             '--reads': 'reads', '--refuse': 'refuses', '--field': 'fields',
             '--link': 'links', '--h2': 'h2s', '--optional-h2': 'optional_h2s',
             '--status-note': 'status_notes'}
    while i < len(argv):
        a = argv[i]
        if a == '--apply':
            o['mode'] = 'apply'
        elif a == '--plan':
            o['mode'] = 'plan'
        elif a in lists:
            i += 1
            o[lists[a]].append(argv[i])
        elif a == '--archetype':
            i += 1
            o['archetypes'] = [x.strip() for x in argv[i].split(',') if x.strip()]
        elif a == '--tools':
            i += 1
            o['tools'] = [x.strip() for x in argv[i].split(',') if x.strip()]
        elif a == '--writes':
            o['writes'] = True
        elif a.startswith('--'):
            i += 1
            o[a[2:]] = argv[i] if i < len(argv) else ''
        else:
            positional.append(a)
        i += 1
    # `verb` and not `kind`: `kind` already names an agent's RETURN kind, and one word meaning
    # two things here wrote 'kind = "agent"' into a return block and was caught by the loader.
    o['positional'] = positional
    o['verb'] = positional[0] if positional else ''
    o['name'] = positional[1] if len(positional) > 1 else ''
    return o


def main():
    o = parse(sys.argv[1:])
    kind, name = o['verb'], o['name']
    print('place %s   author %s' % (VERSION, kind or '(no verb)'))

    if kind not in ('agent', 'workflow', 'class'):
        print('  usage: author.py agent|workflow|class <name> ... [--apply]')
        return 2

    if kind == 'class':
        pos = o['positional']
        op = pos[1] if len(pos) > 1 else ''
        if op not in ('add', 'rename', 'retire'):
            print('  usage: author.py class add|rename|retire <name> ... [--apply]')
            return 2
        cname = pos[2] if len(pos) > 2 else ''
        if op == 'rename':
            return do_rename(o, cname, pos[3] if len(pos) > 3 else '')
        if op == 'retire':
            return do_retire(o, cname)
        o['name'] = name = cname
    if not name or name != name.lower() or '_' in name or ' ' in name:
        print('  a name is required, lowercase kebab-case: got %r' % name)
        return 1

    problems = []
    taken = name_taken(name)
    if taken:
        problems.append(taken)

    if kind == 'agent':
        for req, why in (('job', 'what it is sent to do'),
                         ('returns', 'at least one return field, or nothing can check it'),
                         ('evals', 'at least one eval, or it asserts what it cannot show (D1)')):
            if not o.get(req):
                problems.append('--%s is required: %s' % (req.rstrip('s') if req != 'returns'
                                                          else 'returns', why))
        if o.get('job'):
            over = job_overlap(o['job'], 'agents', 'job')
            if over:
                problems.append(over)
        folder, render = 'agents', agent_toml
    elif kind == 'workflow':
        for req in ('goal', 'input', 'output'):
            if not o.get(req):
                problems.append('--%s is required' % req)
        if len(o['phases']) < 2:
            problems.append('--phase is required at least twice: a single-phase workflow is one '
                            'agent call with ceremony around it')
        if o.get('goal'):
            over = job_overlap(o['goal'], 'workflows', 'goal')
            if over:
                problems.append(over)
        folder, render = 'workflows', workflow_toml

    else:
        for req, why in (('prefix', 'the identifier prefix, uppercase letters'),
                         ('folder', 'where its cards live'),
                         ('purpose', 'one sentence: what one card of this class is'),
                         ('status', 'e.g. "lifecycle=on-review,open;terminal=archived"')):
            if not o.get(req):
                problems.append('--%s is required: %s' % (req, why))
        if not o['fields']:
            problems.append('--field is required at least once. A class whose only content is a status is a checkbox, not a card: it declares a thing to track and nothing to know about it.')
        if not o['archetypes']:
            problems.append('--archetype is required. A class declaration lives in an archetype, never in common/: there is no common/classes and the engine does not look for one.')
        prefix = o.get('prefix') or ''
        if prefix and not (prefix.isupper() and prefix.isalpha()):
            problems.append('prefix %r must be uppercase letters only.' % prefix)
        if prefix and o['archetypes']:
            clash = prefix_taken(prefix, o['archetypes'])
            if clash:
                problems.append(clash)
        if o.get('purpose'):
            over = job_overlap(o['purpose'], 'classes', 'purpose')
            if over:
                problems.append(over)
        for arch in o['archetypes']:
            if not os.path.exists(os.path.join(PKG, 'archetypes', arch, 'manifest.toml')):
                problems.append('no archetype %r in this package.' % arch)
        folder, render = 'classes', class_toml

    if problems:
        print('\nrefused:')
        for p in problems:
            print('  %s' % p)
        return 1

    body = render(name, o)

    # Validate before planning. A declaration that does not load must never reach disk: the next
    # person to run the engine would meet a broken package and no explanation.
    import tempfile
    tmp = os.path.join(tempfile.mkdtemp(prefix='solai-author-'), '%s.toml' % name)
    io.open(tmp, 'w', encoding='utf-8', newline='\n').write(body)
    try:
        {'agent': decl.load_agent, 'workflow': decl.load_workflow,
         'class': decl.load_class}[kind](tmp)
    except decl.DeclError as e:
        print('\nrefused - the declaration this would write does not load:')
        print(e)
        print('\n  Nothing was written. Fix the arguments; the file never reaches disk in this '
              'state.')
        return 1

    plan = fsplan.Plan(PKG, VERSION)
    if kind == 'class':
        # Classes are declared inside the archetype that takes them; agents and workflows
        # are declared once in common/ and selected by name. Writing one class into two
        # archetypes writes the file twice, which is GAP-003 and is reported, not hidden.
        for arch in o['archetypes']:
            plan.write('archetypes/%s/classes/%s.toml' % (arch, name), 'declaration', body)
        if len(o['archetypes']) > 1:
            print('  note: %d copies of this declaration, one per archetype. They will '
                  'drift, because nothing compares them: an archetype cannot extend '
                  'another.' % len(o['archetypes']))
    else:
        plan.write('common/%s/%s.toml' % (folder, name), 'declaration', body)

    notes = []
    for arch in o['archetypes']:
        mpath = os.path.join(PKG, 'archetypes', arch, 'manifest.toml')
        if not os.path.exists(mpath):
            print('\nrefused: no archetype %r at %s' % (arch, mpath))
            return 1
        cur = fsplan.read(mpath)
        new, err = add_to_list(cur, folder, name)
        if err == 'already listed':
            plan.noop('archetypes/%s/manifest.toml' % arch, 'selection', reason='already listed')
            continue
        if err:
            print('\nrefused: %s' % err)
            return 1
        plan.write('archetypes/%s/manifest.toml' % arch, 'selection', new)
        notes.append(arch)

    print()
    print(plan.table())
    if o['mode'] != 'apply':
        print('\nplan only. Nothing written. Re-run with --apply.')
        return 0

    fsplan.apply(plan, os.path.join(PKG, MANIFEST.replace('/', os.sep)),
                 backup_dir=os.path.join(PKG, BACKUP.replace('/', os.sep)))
    print('\napplied.')

    # Prove the package still holds together, from the outside, before claiming success.
    bad = []
    for arch in sorted(os.listdir(os.path.join(PKG, 'archetypes'))):
        try:
            decl.load_archetype(PKG, arch)
        except decl.DeclError as e:
            bad.append('%s:\n%s' % (arch, e))
    if bad:
        print('\nthe package no longer loads. Roll back with:')
        print('  py -c "import sys;sys.path.insert(0,r\'%s\');'
              'from lib import fsplan;print(fsplan.rollback(r\'%s\'))"'
              % (PKG, os.path.join(PKG, MANIFEST.replace('/', os.sep))))
        for b in bad:
            print('\n%s' % b)
        return 1

    print('every archetype still loads.')
    print('\nNext, and this is the part that is not optional: regenerate the projections.')
    print('  py %s/skills/solai-scaffold/scaffold.py "<place>" --apply' % PKG)
    if notes:
        print('Selected into: %s' % ', '.join(notes))
    else:
        print('Declared but selected into no archetype: pass --archetype to wire it in.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
