# -*- coding: utf-8 -*-
"""Author a new agent or workflow declaration, and wire it into the archetypes that take it.

    py author.py agent <name> --job "..." --returns "..." --eval "..." [--archetype a,b] [--apply]
    py author.py workflow <name> --goal "..." --input "..." --output "..." --phase "..." [--apply]

`--plan` is the default and writes nothing, like every other entry point here.

WHY THIS EXISTS. Before it, adding an agent meant editing the package by hand: write a TOML,
remember to add the name to each manifest's list, remember that the list is a top-level key that
TOML swallows if it drifts below a table header, then re-run the engine. Four agents and three
workflows were authored that way, and the cost of that is exactly what these verbs remove.

THE ONE RULE THAT SHAPES IT. A declaration is only written if it LOADS. The content is required
on the command line rather than scaffolded as placeholders, because a placeholder declaration
either fails the loader on the next run - leaving the package broken for whoever runs it next -
or passes it while meaning nothing. So the substantive fields are arguments, the result is
validated in memory before anything is planned, and a refusal names what is missing.

It writes DECLARATIONS only. Projections are regenerated by the engine afterwards, which is the
whole point: nothing here hand-edits a projected file, and the last thing this prints is the
command that regenerates them.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(os.path.dirname(HERE))              # .../plugins/solai
sys.path.insert(0, os.path.dirname(PKG))
sys.path.insert(0, PKG)

from lib import decl, fsplan, VERSION                              # noqa: E402

sys.stdout.reconfigure(encoding='utf-8')

MANIFEST = '.author/last-apply.json'
BACKUP = '.author/_backup'

# Two jobs that share most of their significant words are one job with two names.
#
# CONTAINMENT, not Jaccard. Jaccard divides by the union, so a short job that is entirely a
# SUBSET of a long existing one scores low - and a subset is the clearest duplicate there is.
# Restating scout's first sentence scored 0.43 against its full job and sailed through, which is
# how this was found. Containment divides by the smaller set, so a subset scores 1.0.
OVERLAP = 0.6
STOP = set('a an the and or of to in on for that this it is are be with from by as at not '
           'you your they them what which when each every one two into onto out over under '
           'do does did done its their his her'.split())


def _words(text):
    return {w for w in re.findall(r'[a-z]+', (text or '').lower()) if w not in STOP and len(w) > 2}


def _kv(spec):
    """`key=value;key=value` -> dict. Values may contain anything but a semicolon."""
    out = {}
    for part in spec.split(';'):
        if not part.strip():
            continue
        k, _, v = part.partition('=')
        out[k.strip()] = v.strip()
    return out


def _toml_str(value):
    """A TOML basic string. Multi-line prose is emitted as one line: a declaration field is a
    sentence, not a document, and the loader's minimum lengths are about substance not shape."""
    s = str(value).replace('\\', '\\\\').replace('"', '\\"').replace('\n', ' ')
    return '"%s"' % re.sub(r'\s+', ' ', s).strip()


def _toml_list(values):
    return '[%s]' % ', '.join(_toml_str(v) for v in values)


# --------------------------------------------------------------------------- render

def agent_toml(name, o):
    lines = ['schema = 1', '']
    if o.get('why'):
        lines += ['# %s' % o['why'], '']
    lines += [
        'agent = %s' % _toml_str(name),
        'title = %s' % _toml_str(o.get('title') or name.replace('-', ' ').title()),
        'job   = %s' % _toml_str(o['job']),
    ]
    if o.get('sent-when'):
        lines.append('sent_when = %s' % _toml_str(o['sent-when']))
    lines += [
        'model   = %s' % _toml_str(o.get('model', 'inherit')),
        'tools   = %s' % _toml_list(o.get('tools') or ['Read', 'Grep', 'Glob']),
        'writes  = %s' % ('true' if o.get('writes') else 'false'),
        'induces = %s' % _toml_str(o.get('induces', 'none')),
    ]
    if o.get('reads'):
        lines.append('reads = %s' % _toml_list(o['reads']))
    if o.get('refuses'):
        lines.append('refusals = %s' % _toml_list(o['refuses']))
    lines += ['', '[returns]',
              'kind    = %s' % _toml_str(o.get('returns-kind', 'records')),
              'meaning = %s' % _toml_str(o.get('returns-meaning', o['job']))]
    for spec in o['returns']:
        d = _kv(spec)
        lines += ['', '[[returns.fields]]',
                  'name     = %s' % _toml_str(d.get('name', '')),
                  'type     = %s' % _toml_str(d.get('type', 'scalar')),
                  'required = %s' % ('true' if d.get('required', 'true') != 'false' else 'false')]
        if d.get('values'):
            lines.append('values   = %s' % _toml_list(d['values'].split(',')))
        if d.get('of'):
            lines.append('of       = %s' % _toml_list(d['of'].split(',')))
        lines.append('meaning  = %s' % _toml_str(d.get('meaning', '')))
    for spec in o['evals']:
        d = _kv(spec)
        lines += ['', '[[evals]]',
                  'id         = %s' % _toml_str(d.get('id', '')),
                  'asserts    = %s' % _toml_str(d.get('asserts', '')),
                  'fails_when = %s' % _toml_str(d.get('fails_when', d.get('fails', '')))]
    return '\n'.join(lines) + '\n'


def workflow_toml(name, o):
    lines = ['schema = 1', '']
    if o.get('why'):
        lines += ['# %s' % o['why'], '']
    lines += [
        'workflow = %s' % _toml_str(name),
        'title    = %s' % _toml_str(o.get('title') or name.replace('-', ' ').title()),
        'goal     = %s' % _toml_str(o['goal']),
        'input    = %s' % _toml_str(o['input']),
        'output   = %s' % _toml_str(o['output']),
    ]
    if o.get('run-when'):
        lines.append('run_when = %s' % _toml_str(o['run-when']))
    for i, spec in enumerate(o['phases'], 1):
        d = _kv(spec)
        lines += ['', '[[phases]]',
                  'n     = %d' % i,
                  'title = %s' % _toml_str(d.get('title', '')),
                  'agent = %s' % _toml_str(d.get('agent', '')),
                  'shape = %s' % _toml_str(d.get('shape', 'pipeline')),
                  'over  = %s' % _toml_str(d.get('over', ''))]
        if d.get('carry'):
            lines.append('carry = %s' % _toml_str(d['carry']))
        if d.get('barrier_because') or d.get('because'):
            lines.append('barrier_because = %s'
                         % _toml_str(d.get('barrier_because') or d.get('because')))
        if d.get('detail'):
            lines.append('detail = %s' % _toml_str(d['detail']))
    return '\n'.join(lines) + '\n'


# --------------------------------------------------------------------------- manifest wiring

def add_to_list(text, key, name):
    """Append `name` to the top-level `key = [...]` line. Returns None when already present.

    The list is a TOML top-level key, so it must stay above the first table header: this edits
    the existing line in place rather than appending a new one anywhere, because a `key = [...]`
    written below a table header is silently swallowed into that table.
    """
    rx = re.compile(r'(?m)^(%s\s*=\s*\[)([^\]]*)(\])' % re.escape(key))
    m = rx.search(text)
    if not m:
        return None, '%s: no top-level `%s = [...]` line to extend' % (key, key)
    inner = m.group(2).strip()
    if re.search(r'"%s"' % re.escape(name), inner):
        return None, 'already listed'
    new_inner = ('%s, "%s"' % (inner, name)) if inner else '"%s"' % name
    return text[:m.start()] + m.group(1) + new_inner + m.group(3) + text[m.end():], None


# --------------------------------------------------------------------------- checks

def existing(kind):
    """Every declaration of this kind the package ships, from both search paths."""
    out = {}
    roots = [os.path.join(PKG, 'common', kind)]
    roots += [os.path.join(PKG, 'archetypes', a, kind)
              for a in sorted(os.listdir(os.path.join(PKG, 'archetypes')))]
    for r in roots:
        if not os.path.isdir(r):
            continue
        for f in sorted(os.listdir(r)):
            if f.endswith('.toml'):
                out[f[:-5]] = os.path.join(r, f)
    return out


def name_taken(name):
    """A name is one thing. An agent, a workflow and a card skill share one namespace."""
    for kind, label in (('agents', 'agent'), ('workflows', 'workflow'), ('classes', 'class')):
        if name in existing(kind):
            return 'the name %r is already a declared %s' % (name, label)
    return None


def job_overlap(job, kind='agents', field='job'):
    for other, path in sorted(existing(kind).items()):
        try:
            data = decl._read(path)
        except Exception:                                           # noqa: BLE001
            continue
        theirs = _words(data.get(field, ''))
        mine = _words(job)
        if not theirs or not mine:
            continue
        shared = len(mine & theirs) / float(min(len(mine), len(theirs)))
        if shared >= OVERLAP:
            return ('the declared %s repeats %d%% of the significant words in %r. Two jobs that '
                    'share most of their words are one job with two names: either sharpen this one '
                    'until it is doing something %r is not, or extend %r instead.'
                    % (field, round(shared * 100), other, other, other))
    return None


# --------------------------------------------------------------------------- main

def parse(argv):
    o = {'archetypes': [], 'returns': [], 'evals': [], 'phases': [], 'tools': [],
         'reads': [], 'refuses': [], 'mode': 'plan'}
    i, positional = 0, []
    lists = {'--returns': 'returns', '--eval': 'evals', '--phase': 'phases',
             '--reads': 'reads', '--refuse': 'refuses'}
    while i < len(argv):
        a = argv[i]
        if a == '--apply':
            o['mode'] = 'apply'
        elif a == '--plan':
            o['mode'] = 'plan'
        elif a in lists:
            i += 1
            o[lists[a]].append(argv[i])
        elif a == '--archetype':
            i += 1
            o['archetypes'] = [x.strip() for x in argv[i].split(',') if x.strip()]
        elif a == '--tools':
            i += 1
            o['tools'] = [x.strip() for x in argv[i].split(',') if x.strip()]
        elif a == '--writes':
            o['writes'] = True
        elif a.startswith('--'):
            i += 1
            o[a[2:]] = argv[i] if i < len(argv) else ''
        else:
            positional.append(a)
        i += 1
    # `verb` and not `kind`: `kind` already names an agent's RETURN kind, and one word meaning
    # two things here wrote 'kind = "agent"' into a return block and was caught by the loader.
    o['verb'] = positional[0] if positional else ''
    o['name'] = positional[1] if len(positional) > 1 else ''
    return o


def main():
    o = parse(sys.argv[1:])
    kind, name = o['verb'], o['name']
    print('place %s   author %s' % (VERSION, kind or '(no verb)'))

    if kind not in ('agent', 'workflow'):
        print('  usage: author.py agent|workflow <name> ... [--apply]')
        return 2
    if not name or name != name.lower() or '_' in name or ' ' in name:
        print('  a name is required, lowercase kebab-case: got %r' % name)
        return 1

    problems = []
    taken = name_taken(name)
    if taken:
        problems.append(taken)

    if kind == 'agent':
        for req, why in (('job', 'what it is sent to do'),
                         ('returns', 'at least one return field, or nothing can check it'),
                         ('evals', 'at least one eval, or it asserts what it cannot show (D1)')):
            if not o.get(req):
                problems.append('--%s is required: %s' % (req.rstrip('s') if req != 'returns'
                                                          else 'returns', why))
        if o.get('job'):
            over = job_overlap(o['job'], 'agents', 'job')
            if over:
                problems.append(over)
        folder, render = 'agents', agent_toml
    else:
        for req in ('goal', 'input', 'output'):
            if not o.get(req):
                problems.append('--%s is required' % req)
        if len(o['phases']) < 2:
            problems.append('--phase is required at least twice: a single-phase workflow is one '
                            'agent call with ceremony around it')
        if o.get('goal'):
            over = job_overlap(o['goal'], 'workflows', 'goal')
            if over:
                problems.append(over)
        folder, render = 'workflows', workflow_toml

    if problems:
        print('\nrefused:')
        for p in problems:
            print('  %s' % p)
        return 1

    body = render(name, o)

    # Validate before planning. A declaration that does not load must never reach disk: the next
    # person to run the engine would meet a broken package and no explanation.
    import tempfile
    tmp = os.path.join(tempfile.mkdtemp(prefix='solai-author-'), '%s.toml' % name)
    io.open(tmp, 'w', encoding='utf-8', newline='\n').write(body)
    try:
        (decl.load_agent if kind == 'agent' else decl.load_workflow)(tmp)
    except decl.DeclError as e:
        print('\nrefused - the declaration this would write does not load:')
        print(e)
        print('\n  Nothing was written. Fix the arguments; the file never reaches disk in this '
              'state.')
        return 1

    plan = fsplan.Plan(PKG, VERSION)
    target = 'common/%s/%s.toml' % (folder, name)
    plan.write(target, 'declaration', body)

    notes = []
    for arch in o['archetypes']:
        mpath = os.path.join(PKG, 'archetypes', arch, 'manifest.toml')
        if not os.path.exists(mpath):
            print('\nrefused: no archetype %r at %s' % (arch, mpath))
            return 1
        cur = fsplan.read(mpath)
        new, err = add_to_list(cur, folder, name)
        if err == 'already listed':
            plan.noop('archetypes/%s/manifest.toml' % arch, 'selection', reason='already listed')
            continue
        if err:
            print('\nrefused: %s' % err)
            return 1
        plan.write('archetypes/%s/manifest.toml' % arch, 'selection', new)
        notes.append(arch)

    print()
    print(plan.table())
    if o['mode'] != 'apply':
        print('\nplan only. Nothing written. Re-run with --apply.')
        return 0

    fsplan.apply(plan, os.path.join(PKG, MANIFEST.replace('/', os.sep)),
                 backup_dir=os.path.join(PKG, BACKUP.replace('/', os.sep)))
    print('\napplied.')

    # Prove the package still holds together, from the outside, before claiming success.
    bad = []
    for arch in sorted(os.listdir(os.path.join(PKG, 'archetypes'))):
        try:
            decl.load_archetype(PKG, arch)
        except decl.DeclError as e:
            bad.append('%s:\n%s' % (arch, e))
    if bad:
        print('\nthe package no longer loads. Roll back with:')
        print('  py -c "import sys;sys.path.insert(0,r\'%s\');'
              'from lib import fsplan;print(fsplan.rollback(r\'%s\'))"'
              % (PKG, os.path.join(PKG, MANIFEST.replace('/', os.sep))))
        for b in bad:
            print('\n%s' % b)
        return 1

    print('every archetype still loads.')
    print('\nNext, and this is the part that is not optional: regenerate the projections.')
    print('  py %s/skills/solai-scaffold/scaffold.py "<place>" --apply' % PKG)
    if notes:
        print('Selected into: %s' % ', '.join(notes))
    else:
        print('Declared but selected into no archetype: pass --archetype to wire it in.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
